ERL_LIBS=$(pwd) erl +P 2000000 \
    -pa deps/*/ebin \
    -pa ebin \
    -boot start_sasl \
    -s lager \
    -s inets \
    -s crypto \
    -s ssl  \
    -s industry_app \
    -name industry@$(hostname) \
    -setcookie industries
